### ISSUE TITLE
Sound toggle not working properly on steemitpond

### ISSUE THREAD

**Issue by ayobami99** [bigbhowell/steemitpond#1]
The sound toggle on steemitpond.com is not working properly on mobile. When you visit steemitpond.com
The sound toggle is found on the top right corner of the screen
![20171228_081511_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514445558/fzkdhy0kxlp9prtqfzxz.jpg)

This is automatically on silent, but when clicked the sound icon doesn't change
![20171228_082152_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514445743/kl2bdiydxyg7levsjbfr.jpg)

Instead, it shows a sound icon on the status bar which when viewed is from steemitpond but not playing.
![20171228_081527_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514445625/blor1zghmjrcvdye29pi.jpg)

until you tap the play button on the status bar.
![20171228_081540_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514445642/i6tj6ih9lynn0vavrnlm.jpg)

When the play button is clicked on the status bar, the sound plays but this doesn't change the sound toggle icon which remains on silent.
![20171228_082152_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514445743/kl2bdiydxyg7levsjbfr.jpg)

# How to reproduce
* Go to steemitpond.com
* Click the sound toggle icon

# Video explanation
https://youtu.be/P9YMveTX-oE

# Notes
The sound toggle is supposed to play the sound automatically with the sound icon changing from silent to speaker.

# Browser details
Chrome 63
Phone details: Infinix hot x559c

Thank you.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@ayobami99/sound-not-working-properply-on-steemitpond">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by bigbhowell** [comment]
Fixed. Thanks.
